In [1]:
import numpy as np 
import cv2 
from matplotlib import pyplot as plt 
import cmath 


In [2]:
def DFT_mat(img):

    data = np.asarray(img)
    img_size = data.shape
    
    dft = np.zeros((img_size[0], img_size[1]), dtype = np.complex)

    for I in range(img_size[0]):
        for J in range(img_size[1]):

            mat_sum = 0.0
            for K in range(img_size[0]):
                for L in range(img_size[1]):
                    w = cmath.exp(- 2j * np.pi * ((I * K) / img_size[0] + (J * L) / img_size[1]))

                    mat_sum += data[K, L] * w
            dft[I, J] = mat_sum 
    return dft

In [3]:
arr1 = np.array([[1, 0], [2, 1]])
dft1 = DFT_mat(arr1)

print("Original Matrix: \n")
print(arr1)

print("\n\n")

print("DFT of Matrix: \n")
print(dft1)

Original Matrix: 

[[1 0]
 [2 1]]



DFT of Matrix: 

[[ 4.+0.0000000e+00j  2.-1.2246468e-16j]
 [-2.-3.6739404e-16j  0.+0.0000000e+00j]]


In [9]:
arr2 = np.array([[1,2, 3,4], [5, 6, 7, 8], [9,10,11,12], [13,14,15,16]])
dft2 = DFT_mat(arr2)

print("Original Matrix: \n")
print(arr2)

print("\n\n")

print("DFT of Matrix: \n")
print(dft2)

Original Matrix: 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]



DFT of Matrix: 

[[ 1.36000000e+02+0.00000000e+00j -8.00000000e+00+8.00000000e+00j
  -8.00000000e+00-9.79717439e-15j -8.00000000e+00-8.00000000e+00j]
 [-3.20000000e+01+3.20000000e+01j  3.55271368e-15+1.22712272e-15j
   2.50990696e-15+0.00000000e+00j -2.13162821e-14+6.42753875e-15j]
 [-3.20000000e+01-1.42059029e-14j  3.48838644e-15+0.00000000e+00j
   0.00000000e+00+2.44929360e-15j -6.79864668e-14+3.55271368e-15j]
 [-3.20000000e+01-3.20000000e+01j -2.48689958e-14+2.87482507e-15j
  -8.31807528e-14+3.55271368e-15j -5.68434189e-14+1.90501133e-15j]]


In [12]:
np.fft.fft2(arr2)

array([[136. +0.j,  -8. +8.j,  -8. +0.j,  -8. -8.j],
       [-32.+32.j,   0. +0.j,   0. +0.j,   0. +0.j],
       [-32. +0.j,   0. +0.j,   0. +0.j,   0. +0.j],
       [-32.-32.j,   0. +0.j,   0. +0.j,   0. +0.j]])