In [2]:
import numpy as np

In [3]:
def circulant_array(arr, reps):
    circulant= np.zeros((len(arr), reps))
    circulant[:,0]= np.reshape(arr, (len(arr),))
    
    for i in range(1, reps):
        circulant[:,i]= np.roll(circulant[:,i-1],1)
    return circulant

In [4]:
a = np.array([[1.,2,3],[4,5,6],[7,8,9]])
filt=np.array([[1,2,1],[0,0,0],[-1,-2,-1]])

In [5]:
x0 = circulant_array(filt[(np.shape(filt)[0]-1)-0],len(filt))
x1 = circulant_array(filt[(np.shape(filt)[0]-1)-1],len(filt))
x2 = circulant_array(filt[(np.shape(filt)[0]-1)-2],len(filt))
h1 = np.hstack((x0,x1,x2))
h2 = np.hstack((x2,x0,x1))
h3 = np.hstack((x1,x2,x0))
mat = np.vstack((h1,h2,h3))

x = np.reshape(a,(9,1))
y = np.matmul(mat,x)
y = np.reshape(y,(3,3))

print('Input Array: \n', a)
print('\n Doubly block circulant matrix:\n', mat)
print('\nFilter:\n', filt)
print('\nCircular Convolution:\n', y)

Input Array: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

 Doubly block circulant matrix:
 [[-1. -1. -2.  0.  0.  0.  1.  1.  2.]
 [-2. -1. -1.  0.  0.  0.  2.  1.  1.]
 [-1. -2. -1.  0.  0.  0.  1.  2.  1.]
 [ 1.  1.  2. -1. -1. -2.  0.  0.  0.]
 [ 2.  1.  1. -2. -1. -1.  0.  0.  0.]
 [ 1.  2.  1. -1. -2. -1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  2. -1. -1. -2.]
 [ 0.  0.  0.  2.  1.  1. -2. -1. -1.]
 [ 0.  0.  0.  1.  2.  1. -1. -2. -1.]]

Filter:
 [[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]

Circular Convolution:
 [[ 24.  24.  24.]
 [-12. -12. -12.]
 [-12. -12. -12.]]
